language: node_js
before_deploy: 'yarn build'
node_js:
  - '12.13'
deploy:
  provider: npm
  email: confidenceboi@gmail.com
  api_key:
    secure: $NPM_API_KEY
  on:
    tags: true
    repo: Confidence-Okoghenun/myzuka-dl
  skip_cleanup: 'true'
